---
- name: render env
  when: platform == "reactjs"
  ansible.builtin.template:
    src: env.j2
    dest: "{{ playbook_dir }}/.env"
  vars:
    _next_vars: "{{ vars.keys() | select('match','REACT_APP_.*$') | sort }}"
    
- name: render env nextjs
  when: platform == "nextjs"
  ansible.builtin.template:
    src: env.j2
    dest: "{{ playbook_dir }}/.env"
  vars:
    _next_vars: "{{ vars.keys() | select('match','NEXT_PUBLIC_.*$') | sort }}"